# Generated by Django 5.2.8 on 2025-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приёма на работу"
            ),
        ),
    ]
