# Generated by Django 5.2.8 on 2025-11-28 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "occupied_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workplace",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Занято сотрудником",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место (стол)",
                "verbose_name_plural": "Рабочие места (столы)",
                "ordering": ["table_number"],
            },
        ),
    ]
