# Generated by Django 5.2.8 on 2025-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="table_number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер стола"),
        ),
    ]
