# Generated by Django 5.2.8 on 2025-11-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_workplace_table_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "ordering": ["table_number"],
                "permissions": [
                    ("can_move_employees", "Can move employees between workplaces")
                ],
                "verbose_name": "Рабочее место (стол)",
                "verbose_name_plural": "Рабочие места (столы)",
            },
        ),
    ]
