# Generated by Django 5.2.8 on 2025-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_userimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Порядковый номер"
            ),
        ),
    ]
